<?php
/* 
 * @var $this Zend\View\Renderer\PhpRenderer 
 * @property $container Zend\Navigation\Navigation
 */
/* @var $oPage Zend\Navigation\Page\Mvc */
foreach($this->container as $sKey => $oPage){
    if($oPage->isVisible() && $this->IsAllowed($oPage->getController(), $oPage->getAction()) == true){
?>
<li>
    <a href="<?php echo ($oPage->hasPages() == false) ? $oPage->getHref() : '#'; ?>"><?php 
       if($oPage->get("icon") !== null){
           echo $this->losIcon($oPage->get("icon"), '', true)." ";
       }
       echo $this->translate($oPage->getLabel()); 

       if($oPage->hasPages()){
           echo $this->losIcon("fa arrow");
       }?>
   </a>
    <?php
        if($oPage->hasPages()){
    ?>
    <ul class="nav nav-second-level">
    <?php
        foreach($oPage->getPages() as $oSubPage){
            if($oSubPage->isVisible() && $this->IsAllowed($oSubPage->getController(), $oSubPage->getAction()) == true){
            ?>
        <li>
            <a href="<?php echo $oSubPage->getHref();?>" <?php if($oSubPage->isActive()){echo 'class="active"'; } ?>><?php echo $this->translate($oSubPage->getLabel());?></a>
        </li>
            <?php
            }
        }
    ?>
    </ul>
    <?php
        }
    ?>
</li>
<?php
    }
}
