<?php
/**
 * @property \Zend\Form\Form $oForm 
 */
?>
<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <div class="login-panel panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate("Please Sign In");?></h3>
            </div>
            <div class="panel-body">
                <?php
                    
                    $sAction = $this->url("user/action", array("action" => "login"));
                    $this->oForm->setAttribute("action", $sAction);

                    echo $this->losForm()->openTag($this->oForm);
                    echo $this->losFormRow($this->oForm->get("username"));
                    echo $this->losFormRow($this->oForm->get("password"));
                    echo $this->losFormRow($this->oForm->get("submit")->setAttribute("class", "btn-block btn-success"));
                    echo $this->losForm()->closeTag();
                ?>
            </div>
        </div>
    </div>
</div>