<?php
    $this->PageTitle("USER_SUB_CREATE");

    $sActionUrl = $this->url("user/action", array("action" => "create"));
    $oForm->setAttribute("action", $sActionUrl);
    
    echo $this->losForm()->openTag($oForm);
    echo $this->losFormRow($oForm->get("token"));
?>    
<div class="row">
    <div class="col-md-6">
        <?php
            echo $this->losFormRow($oForm->get("username"));
        ?>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <?php
            echo $this->losFormRow($oForm->get("password"));
        ?>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <?php
            echo $this->losFormRow($oForm->get("role"));
        ?>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="pull-right">
        <?php
            echo $this->losFormRow($oForm->get("submit")->setAttribute("class", "btn btn-primary"));
        ?>    
        </div>
    </div>
</div>
<?php    
    echo $this->losForm()->closeTag();