<?php
    $this->PageTitle("USER_SUB_MANAGEMENT");
?>
<div class="table-responsive">
    <table class="table table-borderless table-striped table-hover">
        <thead>
            <tr>
                <th><?php echo $this->translate("USER_USERNAME");?></th>
                <th><?php echo $this->translate("USER_ROLE");?></th>
                <th><?php echo $this->translate("APPLICATION_ACTION");?></th>
            </tr>
        </thead>
        <tbody>
<?php
    foreach($this->oUserList as $oUser){
?>
            <tr>
                <td><?php echo $oUser->getUsername();?></td>
                <td><?php echo $oUser->getRole()->getRolename();?></td>
                <td>
                    <?php
                        if($this->UserIsAllowed("User", "update")){
                    ?>
                    <a class="btn btn-success btn-sm" href="<?php echo $this->url("user/action", array("action" => "update", "id" => $oUser->getId()));?>"><?php echo $this->translate("APPLICATION_ACTION_EDIT");?></a>
                    <?php
                        }
                    ?>
                </td>
            </tr>
<?php
    }
?> 
        </tbody>
    </table>
</div>
<?php
    
    echo $this->losPaginationControl($this->oUserList)
?>