<?php


/* @var $oVirtualServer \TeamSpeak3\Node\Server */
$oVirtualServer = $this->oVirtualServer;

$this->PageTitle('"'.$oVirtualServer->getProperty("virtualserver_name").'"');
$this->PageTitle("SERVER_VIRTUAL_CHANNEL", 'APPEND');


/* @var $aChannels \TeamSpeak3\Node\Channel[] */
$aChannels = $this->aChannels;
?>
<div class="table-responsive">
    <table class="table table-striped">
        <thead>
            <tr>
                <th><?php echo $this->translate("SERVER_VIRTUAL_CHANNEL_NAME");?></th>
                <th><?php echo $this->translate("SERVER_VIRTUAL_CHANNEL_DESCRIPTION");?></th>
                <th><?php echo $this->translate("SERVER_ACTION");?></th>
            </tr>
        </thead>
        <tbody>
            <?php
                if(count($aChannels) > 0){
                    foreach($aChannels as $oChannel){
                        $aSubChannelList = $oChannel->subChannelList(); // get sub channels
                        if($oChannel->getProperty("pid") == 0){ // is not a sub channel?
            ?>
            <tr>
                <td><?php echo $oChannel->getProperty("channel_name"); ?></td>
                <td><?php echo $oChannel->getProperty("channel_topic"); ?></td>
                <td>
                    <div class="pull-right">

                        <?php
                            if(count($aSubChannelList) > 0){
                        ?>
                        <a href="" class="btn btn-xs btn-primary">
                            <?php
                                echo $this->translate("SERVER_VIRTUAL_CHANNEL");
                            ?>
                        </a>
                        <?php
                            }
                        ?>
                        <a href="" class="btn btn-xs btn-warning"><?php echo $this->translate("SERVER_VIRTUAL_CHANNEL_EDIT");?></a>
                    </div>
                </td>
            </tr>
            <?php
                        }
                    }
                }else{
                    
                }
            ?>
        </tbody>
    </table> 
</div>
