<?php
    /* @var $oVirtualServer \TeamSpeak3\Node\Server */
    $oVirtualServer = $this->oVirtualServer;
    /* @var $aChannels \TeamSpeak3\Node\Channel[] */
    $aChannels      = $this->aChannels;
    
    $this->PageTitle('"'.$oVirtualServer->getProperty("virtualserver_name").'"');
    $this->PageTitle("SERVER_VIRTUAL_CHANNEL", 'APPEND');
?>
<div class="table-responsive">
    <table class="table table-striped">
        <thead>
            <tr>
                <th class="col-md-3"><?php echo $this->translate("SERVER_VIRTUAL_CHANNEL_NAME");?></th>
                <th class="col-md-5"><?php echo $this->translate("SERVER_VIRTUAL_CHANNEL_DESCRIPTION");?></th>
                <th class="col-md-4"><?php echo $this->translate("SERVER_ACTION");?></th>
            </tr>
        </thead>
        <tbody>
            <?php
                if(count($aChannels) > 0){
                    foreach($aChannels as $oChannel){
                        $aSubChannelList = $oChannel->subChannelList(); // get sub channels
                        if($oChannel->getProperty("pid") == 0){ // is not a sub channel?
            ?>
            <tr>
                <td><?php echo nl2br($oChannel->getProperty("channel_name")); ?></td>
                <td ><?php echo $oChannel->getProperty("channel_topic"); ?></td>
                <td>
                    <div class="pull-right">
                        <?php
                            if(count($aSubChannelList) > 0){
                        ?>
                        <a href="" class="btn btn-xs btn-primary">
                            <?php
                                echo $this->translate("SERVER_VIRTUAL_SUB_CHANNEL");
                            ?>
                        </a>
                        <?php
                            }
                        ?>
                        <a href="" class="btn btn-xs btn-warning"><?php echo $this->translate("SERVER_VIRTUAL_CHANNEL_EDIT");?></a>
                        <a href="" class="btn btn-xs btn-danger"><?php echo $this->translate("SERVER_VIRTUAL_CHANNEL_DELETE");?></a>
                    </div>
                </td>
            </tr>
            <?php
                        }
                    }
                }else{
            ?>
            <tr>
                <td colspan="12"><?php echo $this->translate("SERVER_NO_RECORD");?></td>
            </tr>
            <?php
                }
            ?>
        </tbody>
    </table> 
</div>
