<?php
    $this->PageTitle("SERVER_VIRTUAL_MANAGEMENT");
    /* @var $oServer \Server\Entity\Server */
    $oServer        = $this->oServer;
    
    /* @var $oVirtualServer \TeamSpeak3\Node\Server */
    $oVirtualServer = $this->oVirtualServer;
?>
<div class="row">
    <div class="col-sm-12">
        <?php
            $sVirtualChannelUrl = $this->url("server/virtual/action", [
                "action"        => "channelList",
                'id'            => $oServer->getServerID(),
                'virtualId'     => $oVirtualServer->getId(),
            ]);
        ?>
        <a href="<?php echo $sVirtualChannelUrl; ?>" data-placement="top" class="btn btn-lg btn-primary">
            <i class="fa fa-clone fa-4x" list-alt></i><br/><br/>
            <?php echo $this->translate("SERVER_VIRTUAL_CHANNEL");?>
        </a>
        <?php
            $sVirtualGroupsUrl = $this->url("server/virtual/action", [
                "action"        => "serverGroupList",
                'id'            => $oServer->getServerID(),
                'virtualId'     => $oVirtualServer->getId(),
            ]);
        ?>
        <a href="<?php echo $sVirtualGroupsUrl; ?>" data-placement="top" class="btn btn-lg btn-primary">
            <i class="fa fa-group fa-4x list-alt"></i><br/><br/>
            <?php echo $this->translate("SERVER_VIRTUAL_GROUPS");?>
        </a>
        
        <?php
            $sVirtualBackupsUrl = $this->url("server/virtual/action", [
                "action"        => "snapshotList",
                'id'            => $oServer->getServerID(),
                'virtualId'     => $oVirtualServer->getId(),
            ]);
        ?>
        <a href="<?php echo $sVirtualBackupsUrl; ?>" data-placement="top" class="btn btn-lg btn-primary">
            <i class="fa fa-floppy-o fa-4x list-alt"></i><br/><br/>
            <?php echo $this->translate("SERVER_VIRTUAL_SNAPSHOTS");?>
        </a>
    </div>
</div>
