<div class="table-responsive">
    <table class="table table-striped">
        <thead>
            <tr>
                <th class="col-md-8"><?php echo $this->translate("SERVER_VIRTUAL_SNAPSHOT_TIMESTAMP");?></th>
                <th class="col-md-4"><?php echo $this->translate("SERVER_ACTION");?></th>
            </tr>
        </thead>
        <tbody>
            <?php
            /**
             * @var $aSnapshots Doctrine\Common\Collections\ArrayCollection|\Server\Entity\Snapshot[]
             */
                if(count($aSnapshots->count()) > 0){
                    foreach($aSnapshots as $oSnapshot) {
                        ?>
                        <tr>
                            <td><?php echo $oSnapshot->getTimestamp()->format("d.m.Y H:i:s"); ?></td>
                            <td></td>
                        </tr>
                        <?php
                    }
                }else{
            ?>
            <tr>
                <td colspan="12"><?php echo $this->translate("SERVER_NO_RECORD");?></td>
            </tr>
            <?php
                }
            ?>
        </tbody>
    </table>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="pull-right">
            <?php
                $sCreateUrl = $this->url("server/virtual/action", [
                    "action"        => "createSnapshot",
                    'id'            => $oServer->getServerID(),
                    'virtualId'     => $oVirtualServer->getId(),    
                ]);
            ?>
            <a href="<?php echo $sCreateUrl; ?>" class="btn btn-primary"><?php echo $this->translate("SERVER_VIRTUAL_SNAPSHOT_CREATE");?></a>
        </div>
    </div>
</div>