<?php
/**
 * @var \Server\Entity\Snapshot $oSnapshot
 */
$oSnapshot  = $this->oSnapshot;

$this->PageTitle("SERVER_VIRTUAL_SNAPSHOTS_DETAILS");
$this->PageTitle($oSnapshot->getServer()->getServer(), "append");
$this->PageTitle("Snapshot #". $oSnapshot->getSnapshotId(), "append");


?>
<div class="row">
    <div class="col-md-12">
<textarea class="form-control" rows="15" disabled>
<?php
        $sEncConfig    = $oSnapshot->getConfig();
        $sConfig       = base64_decode($sEncConfig);

        echo str_replace(" ", "\n", $sConfig);
?>
</textarea>
    </div>
</div>
