<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle("TS3UI -".$this->translate('APPLICATION_DESCRIPTION'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->appendStylesheet($this->basePath() . '/css/style.css')
                        ->appendStylesheet($this->basePath() . '/bower_components/metisMenu/dist/metisMenu.min.css')
                        ->appendStylesheet($this->basePath() . '/dist/css/timeline.css')
                        ->appendStylesheet($this->basePath() . '/dist/css/sb-admin-2.css')
                        ->appendStylesheet($this->basePath() . '/bower_components/morrisjs/morris.css');
        
            echo $this->losHeadLink();
        ?>
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <div id="wrapper">
            <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url("home");?>">TS3UI</a>
                </div>
                <!-- /.navbar-header -->
                <ul class="nav navbar-top-links navbar-right">
                    <!-- /.dropdown -->
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li><a href="<?php echo $this->url("zfcuser");?>"><i class="fa fa-gear fa-fw"></i> <?php echo $this->translate("USER_EDIT_PROFILE");?></a>
                            </li>
                            <li class="divider"></li>
                            <li><a href="<?php echo $this->url("zfcuser/logout");?>"><i class="fa fa-sign-out fa-fw"></i> <?php echo $this->translate("USER_LOGOUT");?></a>
                            </li>
                        </ul>
                        <!-- /.dropdown-user -->
                    </li>
                    <!-- /.dropdown -->
                </ul>
                <!-- /.navbar-top-links -->
                <div class="navbar-default sidebar" role="navigation">
                    <div class="sidebar-nav navbar-collapse">
                        <ul class="nav" id="side-menu">
                            <?php
                                 echo $this->navigation('navigation')->menu()->setPartial("navigation/vertical")->render();
                            ?>
                        </ul>
                    </div>
                    <!-- /.sidebar-collapse -->
                </div>
                <!-- /.navbar-static-side -->
            </nav>
            <div id="page-wrapper">
                <div class="row">
                    <div class="col-lg-12">
                        <?php echo $this->PageTitle(); ?>
                    </div>
                    <!-- /.col-lg-12 -->
                </div>
                <?php
                    //echo $this->losNavigation('Navigation')->breadcrumbs();
                    echo $this->losFlashMessenger()->renderAll();
                    echo $this->content; 
                ?>
            </div> <!-- /container -->
         </div>
        <!-- Scripts -->
        <?php 
        echo $this->headScript()
            ->appendFile($this->basePath() . '/bower_components/jquery/dist/jquery.min.js')
            ->appendFile($this->basePath() . '/bower_components/bootstrap/dist/js/bootstrap.min.js')
            ->appendFile($this->basePath() . '/bower_components/metisMenu/dist/metisMenu.min.js')
            ->appendFile($this->basePath() . '/bower_components/raphael/raphael-min.js')
            ->appendFile($this->basePath() . '/bower_components/morrisjs/morris.min.js')
            ->appendFile($this->basePath() . '/js/morris-data.js')
            ->appendFile($this->basePath() . '/dist/js/sb-admin-2.js');
            
        echo $this->inlineScript();
        ?>
    </body>
</html>
