<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <?php 
        echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false);   
        echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->appendStylesheet($this->basePath() . '/bower_components/bootstrap/dist/css/bootstrap.min.css')
                        ->appendStylesheet($this->basePath() . '/bower_components/metisMenu/dist/metisMenu.min.css')
                        ->appendStylesheet($this->basePath() . '/dist/css/sb-admin-2.css')
                        ->appendStylesheet($this->basePath() . '/bower_components/font-awesome/css/font-awesome.min.css');
        ?>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body>
    <div class="container">
        <?php
            echo $this->losFlashMessenger()->renderAll();
            echo $this->content; 
        ?>
    </div>
    <!-- jQuery -->
<?php 
    echo $this->headScript()
              ->appendFile($this->basePath() . '/bower_components/jquery/dist/jquery.min.js')
              ->appendFile($this->basePath() . '/bower_components/bootstrap/dist/js/bootstrap.min.js')
              ->appendFile($this->basePath() . '/bower_components/metisMenu/dist/metisMenu.min.js')
              ->appendFile($this->basePath() . '/dist/js/sb-admin-2.js');

    echo $this->inlineScript(); 
?>
</body>

</html>
