<?php

/* 
 * @author         N3X
 * @copyright      Copyright (c) 2015, Ilya Beliaev
 * @since          Version 1.0
 * 
 * $Id$
 * $Date$
 */
/* @var $oForm \Zend\Form\Form */

$sUrl = $this->url("server/action", ["action" => "edit", "id" => $oServer->getServerID()]);

$oForm = $this->oForm;
$oForm->prepare();
$oForm->setAttribute("action", $sUrl);

echo $this->losAlert()->info($this->translate("SERVER_EDIT_INFO"));

echo $this->losForm()->openTag($oForm);
echo $this->losFormRow($oForm->get("token"));
echo $this->losFormRow($oForm->get("serverID"));
?>
<div class="row">
    <div class="col-md-6">
        <?php
            echo $this->losFormRow($oForm->get("username"), false);
        ?>
    </div>
    
</div>
<div class="row">
    <div class="col-md-6">
        <?php
            echo $this->losFormRow($oForm->get("password"), false);
        ?>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <?php
            echo $this->losFormRow($oForm->get("server"), false);
        ?>
    </div>
    <div class="col-md-2">
        <?php
            echo $this->losFormRow($oForm->get("port"), false);
        ?>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="pull-right">
            <?php
                echo $this->losFormRow($oForm->get("submit")->setAttribute("class", "btn btn-primary"));
            ?>
        </div>
    </div>
</div>
<?php
echo $this->losForm()->closeTag();
