<?php

/* 
 * @author         N3X
 * @copyright      Copyright (c) 2015, Ilya Beliaev
 * @since          Version 1.0
 * 
 * $Id$
 * $Date$
 */
$this->PageTitle("SERVER_VIRTUAL");
/* @var $aVirtualServer \TeamSpeak3\Node\Server[] */
$aVirtualServer = $this->aVirtualServer;

?>
<div class="table-responsive">
    <table class="table table-striped">
        <thead>
            <tr>
                <th><?php echo $this->translate("SERVER_VIRTUAL_NAME");?></th>
                <th><?php echo $this->translate("SERVER_VIRTUAL_PORT");?></th>
                <th><?php echo $this->translate("SERVER_VIRTUAL_STATUS");?></th>
                <th><?php echo $this->translate("SERVER_VIRTUAL_PING");?></th>
                
                <th><?php echo $this->translate("SERVER_VIRTUAL_SLOTS");?></th>
                <th><?php echo $this->translate("SERVER_VIRTUAL_VERSION");?></th>
                <th><?php echo $this->translate("SERVER_ACTION");?></th>
            </tr>
        </thead>
        <tbody>
            <?php
            /* @var $oVirtualServer TeamSpeak3\Node\Server */
                foreach($aVirtualServer as $oVirtualServer){
                    
            ?>
            <tr>
                <td><?php echo $this->escapeHtml($oVirtualServer->getProperty("virtualserver_name"));?></td>
                <td><?php echo $oVirtualServer->getProperty("virtualserver_port");?></td>
                <td>
                    <?php 
                        $sStatus = $this->escapeHtml($oVirtualServer->getProperty("virtualserver_status")); 
                        if($sStatus == "online"){
                            echo $this->losLabel()->success(ucfirst($sStatus));
                        }else{
                            echo $this->losLabel()->danger(ucfirst($sStatus));
                        }
                    ?>
                </td>
                <td><?php echo $oVirtualServer->getProperty("virtualserver_total_ping"); ?> ms</td>
                <td><?php echo ($oVirtualServer->getProperty("virtualserver_clientsonline") - $oVirtualServer->getProperty("virtualserver_queryclientsonline"))."/".$oVirtualServer->getProperty("virtualserver_maxclients");?></td>
                <td><?php echo $oVirtualServer->getProperty("virtualserver_version"); ?></td>
                <td>
                    <?php 
                        $sVirtualServerId = $oVirtualServer->getId(); 
                        $sIndexUrl = $this->url("server/virtual/action", ["action" => "index", "id" => $iServerID, "virtualId" => $sVirtualServerId]);
                        $sEditUrl  = $this->url("server/virtual/action", ["action" => "edit", "id" => $iServerID, "virtualId" => $sVirtualServerId]);
                    ?>
                    <a href="<?php echo $sIndexUrl; ?>" class="btn btn-primary btn-xs">
                        <?php
                            echo $this->translate("SERVER_VIRTUAL_MANAGE");
                        ?>
                    </a>
                    
                    <a href="<?php echo $sEditUrl ;?>" class="btn btn-warning btn-xs">
                        <?php
                            echo $this->translate("SERVER_VIRTUAL_EDIT");
                        ?>
                    </a>
                    
                </td>
            </tr>
            <?php
            }
            ?>
        </tbody>
    </table>
</div>



