<?php

/* 
 * @author         N3X
 * @copyright      Copyright (c) 2015, Ilya Beliaev
 * @since          Version 1.0
 * 
 * $Id$
 * $Date$
 */
/* @var $aVirtualServer \TeamSpeak3\Node\Server[] */
$aVirtualServer = $this->aVirtualServer;

?>
<div class="table-responsive">
    <table class="table table-striped">
        <thead>
            <tr>
                <th><?php echo $this->translate("SERVER_VIRTUAL_NAME");?></th>
                <th><?php echo $this->translate("SERVER_VIRTUAL_PORT");?></th>
                <th><?php echo $this->translate("SERVER_VIRTUAL_STATUS");?></th>
                <th><?php echo $this->translate("SERVER_VIRTUAL_SLOTS");?></th>
                <th><?php echo $this->translate("SERVER_VIRTUAL_VERSION");?></th>
                <th><?php echo $this->translate("SERVER_ACTION");?></th>
            </tr>
        </thead>
        <tbody>
            <?php
            /* @var $oVirtualServer TeamSpeak3\Node\Server */
                foreach($aVirtualServer as $oVirtualServer){
            ?>
            <tr>
                <td><?php echo $oVirtualServer->getProperty("virtualserver_name").":".$oVirtualServer->getProperty("virtualserver_port");?></td>
                <td><?php echo $oVirtualServer->getProperty("virtualserver_port");?></td>
                <td><?php echo $oVirtualServer->getProperty("virtualserver_status"); ?></td>
                <td><?php echo $oVirtualServer->getProperty("virtualserver_clientsonline")."/".$oVirtualServer->getProperty("virtualserver_maxclients");?></td>
                <td><?php echo $oVirtualServer->getProperty("virtualserver_version"); ?></td>
                <td><?php echo $oVirtualServer->getId(); ?></td>
            </tr>
            <?php
            }
            ?>
        </tbody>
    </table>
</div>



